### ISSUE TITLE
Use Ingress path fanout instead of hardcoded Nginx locations

### ISSUE THREAD

**Issue by tongpu** [projectcaluma/caluma-demo#15]
Currently the location `^/graphql` is hardcoded in the Nginx configuration. It should be updated to configure the mapping of URL paths to backend services in Ingress. Here's an example what that might look like:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: caluma-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: demo.caluma.io
    http:
      paths:
      - path: /graphql
        backend:
          serviceName: caluma-backend
          servicePort: 8000
      - path: /
        backend:
          serviceName: caluma-assets
          servicePort: 8080
```
